#!/bin/sh

# mkverhdr
# usage: mkverhdr prefix [version]

if [ -n "${1}" ]; then

	if [ "${2}" ]; then
		VERSION=${2}
	else
		VERSION=unknown
	fi

	printf "/* this file is automaticaly generated */\n"
	printf "\n"
	printf "#ifndef ${1}_VERSION_H\n"
	printf "#define ${1}_VERSION_H\n"
	printf "\n"
	printf "#define ${1}_VERSION \"%s\"\n" ${VERSION}
	printf "\n"
	printf "#endif /* ${1}_VERSION_H */\n"
	printf "\n"

else
	echo "usage: mkverhdr prefix [version]"
fi

# end of mkverhdr
